# -*- coding: utf-8 -*-
"""configuration.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hbl3TfKylqIK534Wgwrh5oDbWX6psfYX

Model Parameters
"""

squad_v2=True
max_length=384
doc_stride=128
batch_size=8
n_best_size=20
max_answer_length=30
min_null_score=7.0 
pad_side="right"

#"""Training Parameters"""

evaluation_strategy="epoch"
save_strategy="steps"
save_steps=6000
save_total_limit=1
learning_rate=1.5e-5
adam_epsilon=1e-5
adam_beta1=0.95
adam_beta2=0.999
warmup_steps=100
weight_decay=0.01
tpu_num_cores=8
gradient_accumulation_steps=16

#"""FLAGS value for pipeline"""
do_train = False

#"""Pre-trained Model details"""

# ALBERT Model Information
albert_token_cp = "PremalMatalia/albert-base-best-squad2"
albert_model_cp = "PremalMatalia/albert-base-best-squad2"
albert_savepath = "/content/gdrive/MyDrive/Colab_Notebooks/Master_Project/Saved_models/ALBERT"
albert_train_epoch = 3
albert_NA_threshold= 0

# RoBERTa Model Information
roberta_token_cp = "PremalMatalia/roberta-base-best-squad2"
roberta_model_cp = "PremalMatalia/roberta-base-best-squad2"
roberta_savepath = "/content/gdrive/MyDrive/Colab_Notebooks/Master_Project/Saved_models/RoBERTa"
roberta_train_epoch = 6
roberta_NA_threshold= -3

# ELECTRA Model Information
electra_token_cp = "PremalMatalia/electra-base-best-squad2"
electra_model_cp = "PremalMatalia/electra-base-best-squad2"
electra_savepath = "/content/gdrive/MyDrive/Colab_Notebooks/Master_Project/Saved_models/ELECTRA"
electra_train_epoch = 3
electra_NA_threshold= -3

#"""Final Answer scores Path"""
final_answer_path = "/content/gdrive/MyDrive/Colab_Notebooks/Master_Project/answer_scores/"
final_answer_filename = "_final_score_prediction.csv"